# Generated by Django 3.2.9 on 2021-11-15 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(to='shop.SportCategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.ManyToManyField(to='shop.Gender'),
        ),
        migrations.AlterField(
            model_name='product',
            name='item_type',
            field=models.ManyToManyField(to='shop.OutdoorIndoor'),
        ),
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Unavailable', 'Unavailable')], max_length=200, null=True),
        ),
    ]
